title: ""
logo: /assets/images/logo-32.png
description: "Software Developer • AI/ML"
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default

# GitHub Pages uses kramdown—enable options so MM buttons/HTML render nicely
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


# Top nav links
main:
  - title: "About Me"
    url: "#overview"
  - title: "Skills"
    url: "#skills"
  - title: "Projects"
    url: "#projects"
  - title: "Experience"
    url: "#experience"
  - title: "Education"
    url: "#education"
  - title: "Contact"
    url: "#contact"
  - title: "Resume/CV"
    url: "/assets/resume.pdf"
