title: "Booshra Nazifa Mahmud"
description: "Software Developer • AI/ML"
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

main: []